name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if needed

    - name: Start Flask app
      run: |
        python app.py &  # Run Flask app in the background
        sleep 3  # Allow time for the app to start

    - name: Open Flask app in browser
      run: |
        curl http://localhost:5000  # Open the app in the browser

    - name: Upload image for processing
      run: |
        # Replace 'your_image.jpg' with the actual path to the image you want to upload
        curl -X POST -F "file=@your_image.jpg" http://localhost:5000/upload

    - name: Run predictions with ensemble_4model_final.h5 model
      run: |
        python predict.py  # Replace with the command to run predictions

    - name: Stop Flask app
      run: |
        kill $(jobs -p)  # Stop the Flask app after testing

    - name: Check workflow status
      run: echo "Workflow completed successfully!"
